import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  const response = await fetch(
    "http://localhost:3000/api/exercises"
  );
  const exercises = await response.json();

  return {
    props: { exercises },
  };
}

export default function Home({ exercises }) {
  console.log(exercises);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Open<span>Gym</span>
        </h1>

          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(100px, 1fr))'
          }}>
            {exercises.map(exercise => (
              <div key={exercise.id}>
                <Image src={exercise.gifUrl} width={100} height={100} />
                <p>{exercise.name}</p>
              </div>
            ))}
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
